export const blogList = [
    {
        id: 1,
        img: '/assets/images/sundarbans.jpg',
        name: 'Sundarbans',
        division: 'Khulna',
        district: 'Bagerhat',
        subDistrict: 'Mongla',
        description:
            "Sunderbans, is the largest mangrove forest on earth and a UNESCO World Heritage Site. It spans from the Hooghly River in India’s state of West Bengal to the Baleswar River in Bangladesh. 60% of this mist-shrouded forest is located in Bangladesh. Intersected by a complex network of rivers and creeks, mudflats and tiny islands, this amazing forest is comprised of two elementary eco-regions: mangrove forest and freshwater swamp Forest. It has the rich biodiversity and unique eco-system which boasts of the Royal Bengal tigers, spotted deer, crocodiles, riverine dolphins, wild boars and many more.",
        wiki: 'https://en.wikipedia.org/wiki/Sundarbans',
        maps: 'https://www.google.com/maps/place/%E0%A6%B8%E0%A7%81%E0%A6%A8%E0%A7%8D%E0%A6%A6%E0%A6%B0%E0%A6%AC%E0%A6%A8/@22.019406,88.7264992,9z/data=!3m1!4b1!4m5!3m4!1s0x3a004caac2c7b315:0x4716abcfbb16c93c!8m2!3d21.9497274!4d89.1833304',
    },
    {
        id: 2,
        img: '/assets/images/paharpur.jpg',
        name: 'Paharpur Bihar',
        division: 'Rajshahi',
        district: 'Naogaon',
        subDistrict: 'Badalgachhi',
        description:
            "Sompur Mahabihar or Paharpur Bihar is one of the largest well-known Buddhist Bihar in the South Asia and one of the most popular tourist destinations in the country. This very important archaeological site was designated as a UNESCO World Heritage Site in 1985. The Bihar is located at Paharpur village, Badalgachhi Upazila in Naogaon. Paharpur is the most impressive archeological site of Bangladesh which is known as Sompuri Maharabihara which has declared World Heritage Site by UNESCO and it is situated in the northwestern part of the country. In the initial period, it was the best Buddhist Monastery where people came for higher study from all over the world.",
        wiki: 'https://en.wikipedia.org/wiki/Somapura_Mahavihara',
        maps: 'https://www.google.com/maps/place/%E0%A6%AA%E0%A6%BE%E0%A6%B9%E0%A6%BE%E0%A6%A1%E0%A6%BC%E0%A6%AA%E0%A7%81%E0%A6%B0/@25.0321976,88.9691304,15z/data=!3m1!4b1!4m9!1m2!2m1!1sPaharpur+Bihar!3m5!1s0x39fc8f1cd14f7ff5:0x5d7c353cb03505cb!8m2!3d25.0342023!4d88.9772855!15sCg5QYWhhcnB1ciBCaWhhcpIBDG5laWdoYm9yaG9vZA',
    },
    {
        id: 3,
        img: '/assets/images/CoxsBazaar.png',
        name: 'Chittagong Hill Tracks',
        division: 'Chittagong',
        district: 'Chittagong',
        subDistrict: 'Chittagong',
        description:
            "Hills are always enchanting to the tourist and as a tourist, you should obviously visit Chittagong Hill Tracks once which is the home of many tribal and you can discover yourself in the amazing green view. Chittagong Hill Tracks is the best place for making an adventurous tour and for this you have to take permission from the authority.",
        wiki: 'https://en.wikipedia.org/wiki/Chittagong_Hill_Tracts',
        maps: 'https://www.google.com/maps/place/Chittagong+Hill+Tracts/@22.4660589,91.0738002,8z/data=!3m1!4b1!4m5!3m4!1s0x3752b28e0a33e231:0x80794600bd8d2efe!8m2!3d22.5092405!4d92.2236667',
    },
    {
        id: 4,
        img: '/assets/images/Mahasthangarh.png',
        name: 'Mahasthangarh',
        division: 'Rajshahi',
        district: 'Bogra',
        subDistrict: 'Mahasthan',
        description:
            "Mahasthangarh is one of the earliest urban archaeological sites so far discovered in Bangladesh. It was an important city under the Maurya Empire. The fortified area was in use until the 8th century AD.",
        wiki: 'https://en.wikipedia.org/wiki/Mahasthangarh',
        maps: 'https://www.google.com/maps/place/%E0%A6%AE%E0%A6%B9%E0%A6%BE%E0%A6%B8%E0%A7%8D%E0%A6%A5%E0%A6%BE%E0%A6%A8%E0%A6%97%E0%A7%9C/@24.9505294,89.3331546,14z/data=!4m6!1m2!2m1!1sMahasthangarh!3m2!1s0x39fcfee6067b1e7f:0x549459f98fc4c276!15sCg1NYWhhc3RoYW5nYXJoWg8iDW1haGFzdGhhbmdhcmiSARNoaXN0b3JpY2FsX2xhbmRtYXJrmgEkQ2hkRFNVaE5NRzluUzBWSlEwRm5TVU54ZWxsVGRqZDNSUkFC',
    },
    {
        id: 5,
        img: '/assets/images/SixtyDomeMosque.png',
        name: 'Sixty Dome Mosque',
        division: 'Khulna',
        district: 'Bagerhat',
        subDistrict: 'Bagerhat',
        description:
            "Sixty Dome Mosque more commonly known as Shat Gambuj Mosque is a UNESCO World Heritage Site. It is the largest mosque in Bangladesh from the Sultanate Period (1204-1576). It was built by a Saint General named Khan Jahan Ali near the coast of Bagerhat District of the Sunderbans. The construction of the mosque was started in 1442 and it was completed in 1459.",
        wiki: 'https://en.wikipedia.org/wiki/Sixty_Dome_Mosque',
        maps: 'https://www.google.com/maps/place/%E0%A6%B7%E0%A6%BE%E0%A6%9F+%E0%A6%97%E0%A6%AE%E0%A7%8D%E0%A6%AC%E0%A7%81%E0%A6%9C+%E0%A6%AE%E0%A6%B8%E0%A6%9C%E0%A6%BF%E0%A6%A6/@22.6745068,89.7396472,17z/data=!3m1!4b1!4m5!3m4!1s0x39fff4565f03d17d:0x657f7377a89d5da7!8m2!3d22.6745068!4d89.7418359',
    },
    {
        id: 6,
        img: '/assets/images/CoxsBazaar.png',
        name: 'Cox’s Bazaar',
        division: 'Chittagong',
        district: 'Cox’s Bazaar',
        subDistrict: 'Cox’s Bazaar',
        description:
            "Cox’s Bazaar is a major tourist attraction in Bangladesh. Sloping down to the blue water of the Bay of Bengal against the picturesque backdrop of a series of hills covered with dense forest, Cox’s Bazaar sea beach is the longest sea beach in the world. Its total length is 120 km. It is the place of miles of golden sands, lofty cliffs, surfing waves, amazing conch shells, beautiful pagodas, Buddhist temples and tribes, and mouthwatering seafood. The shark-free beach has its own reputation for bathing, sunbathing, swimming, surfing and many beach rides. The breathtaking beauty of the setting sun behind the vast sea is fascinating.",
        wiki: 'https://en.wikipedia.org/wiki/Cox%27s_Bazar',
        maps: 'https://www.google.com/maps/place/%E0%A6%95%E0%A6%95%E0%A7%8D%E0%A6%B8%E0%A6%AC%E0%A6%BE%E0%A6%9C%E0%A6%BE%E0%A6%B0/@21.4508836,91.9328616,12z/data=!3m1!4b1!4m5!3m4!1s0x30adc7ea2ab928c3:0x3b539e0a68970810!8m2!3d21.4272283!4d92.0058074',
    },
    {
        id: 7,
        img: '/assets/images/SaintMartinsIsland.png',
        name: 'Saint Martin Island',
        division: 'Chittagong',
        district: 'Cox’s Bazaar',
        subDistrict: 'Cox’s Bazaar',
        description:
            "The Saint Martin’s Island is one of the most visited tourist’s spots in Bangladesh. The only coral island in Bangladesh is about 8 km in length and rarely more than 1 km wide. It is about 10 km (6 mi) south-west of the southern tip of the Cox’s Bazaar-Teknaf peninsula. Beaches fringed with coconut palms, panoramic beauty of the island and pristine marine life attract the tourists. Magnificent landscapes, crystal clear sea water, coral colony, and the roar of the Bay of Bengal are the main attraction of the visitors.",
        wiki: 'https://en.wikipedia.org/wiki/St._Martin%27s_Island',
        maps: 'https://www.google.com/maps/search/Saint+Martin/@18.0704999,-63.1321907,12z/data=!3m1!4b1',
    },
    {
        id: 8,
        img: '/assets/images/CoxsBazaar.png',
        name: 'Bandarban',
        division: 'Chittagong',
        district: 'Bandarban',
        subDistrict: 'Bandarban',
        description:
            "Bandarban, literally meaning ‘dam of monkeys’, is a district of Bangladesh in Chittagong Division in Chittagong Hill Tracts area. It has some of the most fascinating tourist attractions of Bangladesh. The beautiful mountain ranges escalate the natural beauty of the surroundings. The largest Buddhist temple of Bangladesh known as Buddha Dhatu Jadi is situated in Bandarban. Also, the peaks like Nilgiri and Thanchi captivate the eyes of the tourists immensely.",
        wiki: 'https://en.wikipedia.org/wiki/Bandarban_District',
        maps: 'https://www.google.com/maps/place/%E0%A6%AC%E0%A6%BE%E0%A6%A8%E0%A7%8D%E0%A6%A6%E0%A6%B0%E0%A6%AC%E0%A6%BE%E0%A6%A8/@24.3058311,91.5574841,11z/data=!4m5!3m4!1s0x30ad6a188414e62b:0xa4c3198f81ba90d0!8m2!3d22.1935628!4d92.2187476',
    },
    {
        id: 9,
        img: '/assets/images/Srimagal.jpg',
        name: 'Srimagal',
        division: 'Sylhet',
        district: 'Moulvibazar',
        subDistrict: 'Srimagal',
        description:
            "The Capital of tea in Bangladesh is Srimagal which is situated in the north-eastern part of the country where you will find lush greenery fields all around. It is one of the best places in Bangladesh where you can really have the place & clam environment and there are two more visiting places too, Lawachhara National Park & Hamham Waterfalls.",
        wiki: 'https://en.wikipedia.org/wiki/Sreemangal_Upazila',
        maps: 'https://www.google.com/maps/place/%E0%A6%B6%E0%A7%8D%E0%A6%B0%E0%A7%80%E0%A6%AE%E0%A6%99%E0%A7%8D%E0%A6%97%E0%A6%B2+%E0%A6%89%E0%A6%AA%E0%A6%9C%E0%A7%87%E0%A6%B2%E0%A6%BE/@24.3058311,91.5574841,11z/data=!3m1!4b1!4m5!3m4!1s0x37517a618ce21b2f:0x6fe8a619a6c2bc3d!8m2!3d24.3064554!4d91.7296439',
    },
    {
        id: 10,
        img: '/assets/images/LalbaghFort.jpg',
        name: 'Lalbag Fort',
        division: 'Dhaka',
        district: 'Lalbagh',
        subDistrict: 'Lalbagh',
        description:
            "The Capital of tea in Bangladesh is Srimagal which is situated in the north-eastern part of the country where you will find lush greenery fields all around. It is one of the best places in Bangladesh where you can really have the place & clam environment and there are two more visiting places too, Lawachhara National Park & Hamham Waterfalls.",
        wiki: 'https://en.wikipedia.org/wiki/Lalbagh_Fort',
        maps: 'https://www.google.com/maps/place/%E0%A6%B2%E0%A6%BE%E0%A6%B2%E0%A6%AC%E0%A6%BE%E0%A6%97+%E0%A6%95%E0%A7%87%E0%A6%B2%E0%A7%8D%E0%A6%B2%E0%A6%BE/@23.7188605,90.3859709,17z/data=!3m1!4b1!4m5!3m4!1s0x3755b8d900000001:0x4e16316ffc66e862!8m2!3d23.7188675!4d90.3881591',
    },
    {
        id: 11,
        img: '/assets/images/StarMosque.jpg',
        name: 'Star Mosque',
        division: 'Dhaka',
        district: 'Old Dhaka',
        subDistrict: 'Old Dhaka',
        description:
            "It is a famous tourist attraction in old Dhaka. The mosque is fully decorated with a mosaic. People also use this mosque for regular praying. Non-muslims are also invited to this mosque outside of prayer time. It was designed by Mughal style and the motifs of stars are the main cause to call this mosque “Star Mosque”.",
        wiki: 'https://en.wikipedia.org/wiki/Star_Mosque',
        maps: 'https://www.google.com/maps/place/%E0%A6%A4%E0%A6%BE%E0%A6%B0%E0%A6%BE+%E0%A6%AE%E0%A6%B8%E0%A6%9C%E0%A6%BF%E0%A6%A6/@23.7156086,90.3994979,17z/data=!3m1!4b1!4m5!3m4!1s0x3755c42daded3c57:0xfd97429a97fe53f5!8m2!3d23.7156086!4d90.4016866',
    },
    {
        id: 12,
        img: '/assets/images/AhsanManzil.jpg',
        name: 'Ahsan Manzil',
        division: 'Dhaka',
        district: 'Dhaka',
        subDistrict: 'Kumartoli',
        description:
            "Ahsan Manzil or the Pink Palace, the most meaningful architectural heritage, was built by Nawab Abdul Gani in 1872. This two-story building is now a museum displaying all kinds of objects of the owner of that time. So you can feel the lifestyle of the Nawabs of Bengal. It has 23 galleries displaying historical things.",
        wiki: 'https://en.wikipedia.org/wiki/Ahsan_Manzil',
        maps: 'https://www.google.com/maps/place/%E0%A6%86%E0%A6%B9%E0%A7%8D%E0%A6%B8%E0%A6%BE%E0%A6%A8+%E0%A6%AE%E0%A6%9E%E0%A7%8D%E0%A6%9C%E0%A6%BF%E0%A6%B2+%E0%A6%9C%E0%A6%BE%E0%A6%A6%E0%A7%81%E0%A6%98%E0%A6%B0/@23.7085464,90.4038441,17z/data=!3m1!4b1!4m5!3m4!1s0x3755b9047a855555:0xdb6be1e307885b57!8m2!3d23.7085464!4d90.4060328',
    },
    {
        id: 13,
        img: '/assets/images/Mujibnagar.jpg',
        name: 'Mujibnagar',
        division: 'Khulna',
        district: 'Meherpur',
        subDistrict: 'Mujibnagar',
        description:
            "Mujibnagar, formerly known as Baidyanathtala (Boiddonathtola) and Bhoborpara, is a town in the Meherpur District of Bangladesh.[2] The First Government of Bangladesh was formed on 10 April 1971, however, sworn in on 17 April 1971 in this place by the elected representatives of the Bengalees (mostly belongling to Awami League), that led the Bangladesh Liberation War, who were leading the guerrilla war for the independence of Bangladesh (then East Pakistan) from Pakistan in 1971.[3] The place was renamed Mujibnagar by the proclamation of independence,[4] in honour of Sheikh Mujibur Rahman, who declared Bangladesh independent.[1] The actual capital of the government while in exile was Calcutta. A memorial complex covering 20.10 acres (8.13 ha) has been built at the site where thed ministers of that first government took their oaths.",
        wiki: 'https://en.wikipedia.org/wiki/Mujibnagar',
        maps: 'https://www.google.com/maps/place/Mujibnagar/@23.6507833,88.5738586,14z/data=!3m1!4b1!4m5!3m4!1s0x39f93bd1f14b1aa1:0xd24ee42cce1dbd04!8m2!3d23.646846!4d88.5927608?hl=en',
    },
    {
        id: 14,
        img: '/assets/images/Nilkuthi.jpg',
        name: 'Amjhupi Neelkuthi',
        division: 'Khulna',
        district: 'Meherpur',
        subDistrict: 'Meherpur',
        description:
            "Amjhupi Nilkuthi is located about six kilometers east of Meherpur town. This kuthi is situated in a beautiful natural environment near the bank of the Kajla river in Dokkhinpara of Amjhupi village. On 13th May 1978, Amjhupi Nilkuthi was considered as a tourist center by the Khulna Development Authority. There has been a belief that this kuthi was the last meeting place of Mir Jafar and the conspirators with Robert Clive, and that's why not only Nawab Siraj-ud-Daula's fate was turnover but also Bengalis lost their freedom.",
        wiki: 'https://bn.wikipedia.org/wiki/%E0%A6%86%E0%A6%AE%E0%A6%9D%E0%A7%81%E0%A6%AA%E0%A6%BF_%E0%A6%A8%E0%A7%80%E0%A6%B2%E0%A6%95%E0%A7%81%E0%A6%A0%E0%A6%BF',
        maps: 'https://www.google.com/maps/place/Amjhupi+Neelkuthi/@23.7412349,88.6759974,17z/data=!3m1!4b1!4m5!3m4!1s0x39f9363141a4c8d5:0xd61a22d66322b4b0!8m2!3d23.741235!4d88.6781868?hl=en',
    },
    {
        id: 15,
        img: '/assets/images/BhatparaNeelkuthi.jpg',
        name: 'Bhatpara Neelkuthi',
        division: 'Khulna',
        district: 'Meherpur',
        subDistrict: 'Meherpur',
        description:
            "Bhatpara Neelkuthi (Bengali: ভাটপাড়া নীলিকুঠি) is a ruined indigo factory situated in Gangni Upazila of Meherpur District, Bangladesh. It was built by the British in 1778. It is about 17 kilometres (11 mi) from Meherpur town. There is a mango garden beside the cottage. There is also a ruined church on the northwest part of the garden. A very shallow river named Kazla flows by the Neelkuthi. It's contemporary to amjhupi Neelkuthi.",
        wiki: 'https://en.wikipedia.org/wiki/Bhatpara_Neelkuthi',
        maps: 'https://www.google.com/maps/place/Bhatpara+Nilkuthi+and+DC+Eco+park/@23.8462515,88.699533,17z/data=!3m1!4b1!4m5!3m4!1s0x39f94951e5203d3d:0x9a4dd3c55d456071!8m2!3d23.8462515!4d88.7017217?hl=en',
    },

    /* {
        id: 2,
        title: 'Milan Places That Highlight The City',
        category: 'travel',
        subCategory: ['vacation', 'holidays', 'sight seeing'],
        description:
            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
        authorName: 'John Doe',
        authorAvatar: '/assets/images/author.jpg',
        createdAt: 'June 03, 2021',
        cover: '/assets/images/f67396fc3cfce63a28e07ebb35d974ac.jpg',
    }, */
];